[
    {
      "Matches": [],
      "AverageMatchRank": 0.0,
      "PrvIdn": "100079190",
      "ProviderNpi": "1/1/2010",
      "EffectiveDt": "",
      "TermDt": "GPS Associate",
      "FacilityName": "Gatting",
      "LastName": "Gatting",
      "FirstName": "Bruce",
      "MiddleName": "W.",
      "SuffixName": "MD",
      "ProviderSpecialityCode": "",
      "ProviderSpecialityDesc": "",
      "ProviderCity": "Chisago City",
      "ProviderCounty": "Chisago",
      "ProviderState": "MN",
      "ProviderZip": "98007",
      "DeaNumber": "�XXXXA29801",
      "StateLicense": "XXXXX682533",
      "TaxId": "userSysNbr",
      "CreateTimestamp": "02:03.4",
      "ModifyTimestamp": null,
      "Keywords": "General ophthalmology; dry eye; medical glaucoma Secondary cataract laser surgery (Yag posterior capsulotomy) Minor eyelid lesion removal (excisional biopsies) Punctal plugs for dry eyes Glaucoma laser surgery (Selective laser trabeculoplasty; Argon laser trabeculoplasty; peripheral iridotomy) Electrolysis or forcep epilation for trichiasis (misdirected eyelashes) Examinations for diabetic eye disease and macular degeneration; General comprehensive ophthalmology; dry eye; medical glaucoma; glaucoma laser; after-cataract laser; rosacea; ocular rosacea",
      "Price": "12567",
      "Distance": "4.14 mi"
    },
    {
      "Matches": [],
      "AverageMatchRank": 0.0,
      "PrvIdn": "100186930",
      "ProviderNpi": "1/1/2010",
      "EffectiveDt": "",
      "TermDt": "Proliance Surgeons",
      "FacilityName": "Pichowsky",
      "LastName": "Pichowsky",
      "FirstName": "Robert",
      "MiddleName": "S.",
      "SuffixName": "MD",
      "ProviderSpecialityCode": "",
      "ProviderSpecialityDesc": "",
      "ProviderCity": "Saint Paul",
      "ProviderCounty": "Ramsey",
      "ProviderState": "MN",
      "ProviderZip": "98005",
      "DeaNumber": "XXXXA10747",
      "StateLicense": "XXXXX954367",
      "TaxId": "userSysNbr",
      "CreateTimestamp": "01:59.5",
      "ModifyTimestamp": null,
      "Keywords": "Ophthalmology; Minimally Invasive Surgery",
      "Price": "9485",
      "Distance": "2.37 mi"
    },
    {
      "Matches": [],
      "AverageMatchRank": 0.0,
      "PrvIdn": "100064180",
      "ProviderNpi": "1/1/2010",
      "EffectiveDt": "",
      "TermDt": "Retinal Associates",
      "FacilityName": "Graham",
      "LastName": "Graham",
      "FirstName": "Bell",
      "MiddleName": "",
      "SuffixName": "MD",
      "ProviderSpecialityCode": "",
      "ProviderSpecialityDesc": "",
      "ProviderCity": "Circle Pines",
      "ProviderCounty": "Anoka",
      "ProviderState": "MN",
      "ProviderZip": "55014",
      "DeaNumber": "XXXXA40940",
      "StateLicense": "XXXXX667874",
      "TaxId": "userSysNbr",
      "CreateTimestamp": "01:59.3",
      "ModifyTimestamp": null,
      "Keywords": "Ophthalmology; Vitreoretinal Surgery; Minimally Invasive Surgery; Medical and surgical diseases of the retina and vitreous; including age-related macular degeneration; diabetic retinopathy; retinal detachments; retinal dystrophies; Medical and surgical diseases of the retina and vitreous; including age-related macular degeneration; diabetic retinopathy and retinal detachments",
      "Price": "8769",
      "Distance": "1657.37 mi"
    },
    {
      "Matches": [],
      "AverageMatchRank": 0.0,
      "PrvIdn": "100002390",
      "ProviderNpi": "1/1/2010",
      "EffectiveDt": "",
      "TermDt": "VM healthcare",
      "FacilityName": "Chang",
      "LastName": "Chang",
      "FirstName": "William",
      "MiddleName": "",
      "SuffixName": "MD",
      "ProviderSpecialityCode": "",
      "ProviderSpecialityDesc": "",
      "ProviderCity": "Anoka",
      "ProviderCounty": "Anoka",
      "ProviderState": "MN",
      "ProviderZip": "98008",
      "DeaNumber": "XXXXA30361",
      "StateLicense": "XXXXX537085",
      "TaxId": "userSysNbr",
      "CreateTimestamp": "00:41.0",
      "ModifyTimestamp": null,
      "Keywords": "Small-incision phacoemulsification cataract surgery; minor in-office procedures including small eyelid anomalies and chalazion excisions and laser surgical procedures for secondary cataracts; glaucoma and diabetic complications; General ophthalmology including cataract surgery; glaucoma and diabetic care",
      "Price": "24000",
      "Distance": "5.51 mi"
    },
    {
      "Matches": [],
      "AverageMatchRank": 0.0,
      "PrvIdn": "100052790",
      "ProviderNpi": "1/1/2010",
      "EffectiveDt": "",
      "TermDt": "Swedish ",
      "FacilityName": "Park",
      "LastName": "Park",
      "FirstName": "Lisa",
      "MiddleName": "",
      "SuffixName": "MD",
      "ProviderSpecialityCode": "",
      "ProviderSpecialityDesc": "",
      "ProviderCity": "Bethel",
      "ProviderCounty": "Anoka",
      "ProviderState": "MN",
      "ProviderZip": "98004",
      "DeaNumber": "XXXXG59365",
      "StateLicense": "XXXXX537504",
      "TaxId": "userSysNbr",
      "CreateTimestamp": "01:27.9",
      "ModifyTimestamp": null,
      "Keywords": "Ophthalmology; Vitreoretinal Surgery; Minimally Invasive Surgery; Medical and surgical diseases of the retina and vitreous; including age-related macular degeneration; diabetic retinopathy; retinal detachments; retinal dystrophies",
      "Price": "13578",
      "Distance": "0.00 mi"
    },
    {
      "Matches": [],
      "AverageMatchRank": 0.0,
      "PrvIdn": "100073550",
      "ProviderNpi": "1/1/2010",
      "EffectiveDt": "",
      "TermDt": "UW",
      "FacilityName": "Webbing",
      "LastName": "Webbing",
      "FirstName": "Marianna",
      "MiddleName": "",
      "SuffixName": "MD",
      "ProviderSpecialityCode": "",
      "ProviderSpecialityDesc": "",
      "ProviderCity": "Center City",
      "ProviderCounty": "Chisago",
      "ProviderState": "MN",
      "ProviderZip": "98001",
      "DeaNumber": "�XXXXA29800",
      "StateLicense": "XXXXX672132",
      "TaxId": "userSysNbr",
      "CreateTimestamp": "01:59.4",
      "ModifyTimestamp": null,
      "Keywords": "Pediatric Ophthalmology; Ophthalmology; Cataract Surgery; Strabismus; Pediatric ophthalmology; adult strabismus (misaligned eyes); strabismus surgery and cataract surgery",
      "Price": "18756",
      "Distance": "23.39 mi"
    },
    {
      "Matches": [],
      "AverageMatchRank": 0.0,
      "PrvIdn": "100106860",
      "ProviderNpi": "1/1/2010",
      "EffectiveDt": "",
      "TermDt": "Proliance Surgeons",
      "FacilityName": "Osborne",
      "LastName": "Osborne",
      "FirstName": "Sarah",
      "MiddleName": "M.",
      "SuffixName": "MD",
      "ProviderSpecialityCode": "",
      "ProviderSpecialityDesc": "",
      "ProviderCity": "Champlin",
      "ProviderCounty": "Hennepin",
      "ProviderState": "MN",
      "ProviderZip": "98008",
      "DeaNumber": "XXXXA20279",
      "StateLicense": "XXXXX833770",
      "TaxId": "userSysNbr",
      "CreateTimestamp": "01:59.4",
      "ModifyTimestamp": null,
      "Keywords": "Sports medicine; Orthopedic rehabilitation; Vestibular rehabilitation",
      "Price": "9018",
      "Distance": "5.51 mi"
    },
    {
      "Matches": [],
      "AverageMatchRank": 0.0,
      "PrvIdn": "100215340",
      "ProviderNpi": "1/1/2010",
      "EffectiveDt": "",
      "TermDt": "",
      "FacilityName": "Doctor Last Name 20",
      "LastName": "Doctor Last Name 20",
      "FirstName": "Doctor First Name 20",
      "MiddleName": "Doctor Middle Name 20",
      "SuffixName": "MD",
      "ProviderSpecialityCode": "",
      "ProviderSpecialityDesc": "",
      "ProviderCity": "Elk River",
      "ProviderCounty": "Sherburne",
      "ProviderState": "MN",
      "ProviderZip": "55330",
      "DeaNumber": "XXXXA30933",
      "StateLicense": "XXXXX036581",
      "TaxId": "userSysNbr",
      "CreateTimestamp": "02:05.9",
      "ModifyTimestamp": null,
      "Keywords": "Ophthalmology; Cataract Surgery; Cornea & Eye Disease; Minimally Invasive Surgery",
      "Price": "2378",
      "Distance": "1627.78 mi"
    },
    {
      "Matches": [],
      "AverageMatchRank": 0.0,
      "PrvIdn": "100162870",
      "ProviderNpi": "1/1/2010",
      "EffectiveDt": "",
      "TermDt": "Proliance Surgeons",
      "FacilityName": "Morris",
      "LastName": "Morris",
      "FirstName": "Taylor",
      "MiddleName": "",
      "SuffixName": "MD",
      "ProviderSpecialityCode": "",
      "ProviderSpecialityDesc": "",
      "ProviderCity": "Minneapolis",
      "ProviderCounty": "Hennepin",
      "ProviderState": "MN",
      "ProviderZip": "98004",
      "DeaNumber": "�XXXXA44847",
      "StateLicense": "XXXXX924530",
      "TaxId": "userSysNbr",
      "CreateTimestamp": "02:12.1",
      "ModifyTimestamp": null,
      "Keywords": "Foot and Ankle Surgery; Orthopedic Surgery; Podiatric Surgery; Orthopedics; Podiatry; Minimally Invasive Surgery; Wound Care",
      "Price": "3869",
      "Distance": "0.00 mi"
    },
    {
      "Matches": [],
      "AverageMatchRank": 0.0,
      "PrvIdn": "100105420",
      "ProviderNpi": "1/1/2010",
      "EffectiveDt": "",
      "TermDt": "Swedish ",
      "FacilityName": "Orson",
      "LastName": "Orson",
      "FirstName": "Rick",
      "MiddleName": "",
      "SuffixName": "MD",
      "ProviderSpecialityCode": "",
      "ProviderSpecialityDesc": "",
      "ProviderCity": "Lakeville",
      "ProviderCounty": "Dakota",
      "ProviderState": "MN",
      "ProviderZip": "98000",
      "DeaNumber": "XXXXG75426",
      "StateLicense": "XXXXX818454",
      "TaxId": "userSysNbr",
      "CreateTimestamp": "01:42.9",
      "ModifyTimestamp": null,
      "Keywords": "Orthopedic Surgery; Sports Medicine; Hip & Knee Joint Replacement; Orthopedics; Minimally Invasive Surgery",
      "Price": "6500",
      "Distance": null
    },
    {
      "Matches": [],
      "AverageMatchRank": 0.0,
      "PrvIdn": "100164000",
      "ProviderNpi": "1/1/2010",
      "EffectiveDt": "",
      "TermDt": "Eric Eid Private Ltd",
      "FacilityName": "Eid",
      "LastName": "Eid",
      "FirstName": "Eric",
      "MiddleName": "T.",
      "SuffixName": "MD",
      "ProviderSpecialityCode": "",
      "ProviderSpecialityDesc": "",
      "ProviderCity": "Minneapolis",
      "ProviderCounty": "Hennepin",
      "ProviderState": "MN",
      "ProviderZip": "98881",
      "DeaNumber": "XXXXA44694",
      "StateLicense": "XXXXX940109",
      "TaxId": "userSysNbr",
      "CreateTimestamp": "01:07.7",
      "ModifyTimestamp": null,
      "Keywords": "Orthopedic Surgery; Orthopedics; Orthopedic Oncology; Minimally Invasive Surgery; Hip & Knee Joint Replacement",
      "Price": "2957",
      "Distance": null
    },
    {
      "Matches": [],
      "AverageMatchRank": 0.0,
      "PrvIdn": "100154540",
      "ProviderNpi": "1/1/2010",
      "EffectiveDt": "",
      "TermDt": "Peterson Practice",
      "FacilityName": "Peterson",
      "LastName": "Peterson",
      "FirstName": "Thomas",
      "MiddleName": "L.",
      "SuffixName": "MD",
      "ProviderSpecialityCode": "",
      "ProviderSpecialityDesc": "",
      "ProviderCity": "Minneapolis",
      "ProviderCounty": "Hennepin",
      "ProviderState": "MN",
      "ProviderZip": "98073",
      "DeaNumber": "XXXXA78358",
      "StateLicense": "XXXXX921742",
      "TaxId": "userSysNbr",
      "CreateTimestamp": "02:08.9",
      "ModifyTimestamp": null,
      "Keywords": "Orthopedic Surgery; Orthopedics; Sports Medicine; Hip & Knee Joint Replacement; Minimally Invasive Surgery",
      "Price": "9405",
      "Distance": "8.20 mi"
    },
    {
      "Matches": [],
      "AverageMatchRank": 0.0,
      "PrvIdn": "100133100",
      "ProviderNpi": "1/1/2010",
      "EffectiveDt": "",
      "TermDt": "Huck Associates",
      "FacilityName": "Huck",
      "LastName": "Huck",
      "FirstName": "Steven",
      "MiddleName": "R.",
      "SuffixName": "MD",
      "ProviderSpecialityCode": "",
      "ProviderSpecialityDesc": "",
      "ProviderCity": "Hopkins",
      "ProviderCounty": "Hennepin",
      "ProviderState": "MN",
      "ProviderZip": "98053",
      "DeaNumber": "XXXXA16220",
      "StateLicense": "XXXXX910802",
      "TaxId": "userSysNbr",
      "CreateTimestamp": "02:01.5",
      "ModifyTimestamp": null,
      "Keywords": "Orthopedic Surgery; Orthopedics; Sports Medicine",
      "Price": "7558",
      "Distance": "13.26 mi"
    },
    {
      "Matches": [],
      "AverageMatchRank": 0.0,
      "PrvIdn": "100132730",
      "ProviderNpi": "1/1/2010",
      "EffectiveDt": "",
      "TermDt": "Proliance Surgeons",
      "FacilityName": "Gordon",
      "LastName": "Gordon",
      "FirstName": "John",
      "MiddleName": "",
      "SuffixName": "MD",
      "ProviderSpecialityCode": "",
      "ProviderSpecialityDesc": "",
      "ProviderCity": "Eden Prairie",
      "ProviderCounty": "Hennepin",
      "ProviderState": "MN",
      "ProviderZip": "98073",
      "DeaNumber": "XXXXA16219",
      "StateLicense": "XXXXX873856",
      "TaxId": "userSysNbr",
      "CreateTimestamp": "01:59.5",
      "ModifyTimestamp": null,
      "Keywords": "Orthopedics",
      "Price": "6335",
      "Distance": "8.20 mi"
    },
    {
      "Matches": [],
      "AverageMatchRank": 0.0,
      "PrvIdn": "100207670",
      "ProviderNpi": "1/1/2010",
      "EffectiveDt": "",
      "TermDt": "Proliance Surgeons",
      "FacilityName": "Carlson",
      "LastName": "Carlson",
      "FirstName": "Jeffery",
      "MiddleName": "",
      "SuffixName": "MD",
      "ProviderSpecialityCode": "",
      "ProviderSpecialityDesc": "",
      "ProviderCity": "Saint Paul",
      "ProviderCounty": "Ramsey",
      "ProviderState": "MN",
      "ProviderZip": "98493",
      "DeaNumber": "XXXXB104622",
      "StateLicense": "XXXXX019942",
      "TaxId": "userSysNbr",
      "CreateTimestamp": "02:01.6",
      "ModifyTimestamp": null,
      "Keywords": "Ophthalmology; Vitreoretinal Surgery; Minimally Invasive Surgery",
      "Price": "6738",
      "Distance": null
    },
    {
      "Matches": [],
      "AverageMatchRank": 0.0,
      "PrvIdn": "100102190",
      "ProviderNpi": "1/1/2010",
      "EffectiveDt": "",
      "TermDt": "VM healthcare",
      "FacilityName": "Neilson",
      "LastName": "Neilson",
      "FirstName": "Abby",
      "MiddleName": "",
      "SuffixName": "MD",
      "ProviderSpecialityCode": "",
      "ProviderSpecialityDesc": "",
      "ProviderCity": "Inver Grove Heights",
      "ProviderCounty": "Dakota",
      "ProviderState": "MN",
      "ProviderZip": "98101",
      "DeaNumber": "XXXXB3963",
      "StateLicense": "XXXXX806087",
      "TaxId": "userSysNbr",
      "CreateTimestamp": "01:08.8",
      "ModifyTimestamp": null,
      "Keywords": "Orthopedic Surgery; Sports Medicine; Orthopedics",
      "Price": "3224",
      "Distance": "9.95 mi"
    },
    {
      "Matches": [],
      "AverageMatchRank": 0.0,
      "PrvIdn": "100092080",
      "ProviderNpi": "1/1/2010",
      "EffectiveDt": "",
      "TermDt": "UW",
      "FacilityName": "Mallard",
      "LastName": "Mallard",
      "FirstName": "David",
      "MiddleName": "L.",
      "SuffixName": "MD",
      "ProviderSpecialityCode": "",
      "ProviderSpecialityDesc": "",
      "ProviderCity": "Burnsville",
      "ProviderCounty": "Dakota",
      "ProviderState": "MN",
      "ProviderZip": "98191",
      "DeaNumber": "XXXXB12934",
      "StateLicense": "XXXXX747058",
      "TaxId": "userSysNbr",
      "CreateTimestamp": "02:15.2",
      "ModifyTimestamp": null,
      "Keywords": "Sports Medicine; Orthopedics",
      "Price": "4371",
      "Distance": null
    },
    {
      "Matches": [],
      "AverageMatchRank": 0.0,
      "PrvIdn": "100089030",
      "ProviderNpi": "1/1/2010",
      "EffectiveDt": "",
      "TermDt": "Providence",
      "FacilityName": "Lee",
      "LastName": "Lee",
      "FirstName": "Andrew",
      "MiddleName": "",
      "SuffixName": "MD",
      "ProviderSpecialityCode": "",
      "ProviderSpecialityDesc": "",
      "ProviderCity": "Taylors Falls",
      "ProviderCounty": "Chisago",
      "ProviderState": "MN",
      "ProviderZip": "98084",
      "DeaNumber": "XXXXA12166",
      "StateLicense": "XXXXX744468",
      "TaxId": "userSysNbr",
      "CreateTimestamp": "02:05.9",
      "ModifyTimestamp": null,
      "Keywords": "Orthopedic Surgery; Orthopedics; Sports Medicine; Minimally Invasive Surgery",
      "Price": "4539",
      "Distance": null
    },
    {
      "Matches": [],
      "AverageMatchRank": 0.0,
      "PrvIdn": "100169810",
      "ProviderNpi": "1/1/2010",
      "EffectiveDt": "",
      "TermDt": "UW sports medicine",
      "FacilityName": "Mars",
      "LastName": "Mars",
      "FirstName": "Kevin",
      "MiddleName": "",
      "SuffixName": "MD",
      "ProviderSpecialityCode": "",
      "ProviderSpecialityDesc": "",
      "ProviderCity": "Minneapolis",
      "ProviderCounty": "Hennepin",
      "ProviderState": "MN",
      "ProviderZip": "98004",
      "DeaNumber": "XXXXA45224",
      "StateLicense": "XXXXX945477",
      "TaxId": "userSysNbr",
      "CreateTimestamp": "01:42.7",
      "ModifyTimestamp": null,
      "Keywords": "Orthopedics; Orthopedic Surgery; Sports Medicine; Knee & Shoulder Reconstruction; Minimally Invasive Surgery",
      "Price": "4883",
      "Distance": "0.00 mi"
    },
    {
      "Matches": [],
      "AverageMatchRank": 0.0,
      "PrvIdn": "100205660",
      "ProviderNpi": "1/1/2010",
      "EffectiveDt": "",
      "TermDt": "Proliance Surgeons",
      "FacilityName": "Chen",
      "LastName": "Chen",
      "FirstName": "Julian",
      "MiddleName": "R.",
      "SuffixName": "MD",
      "ProviderSpecialityCode": "",
      "ProviderSpecialityDesc": "",
      "ProviderCity": "Saint Paul",
      "ProviderCounty": "Ramsey",
      "ProviderState": "MN",
      "ProviderZip": "98483",
      "DeaNumber": "XXXXB104621",
      "StateLicense": "XXXXX975968",
      "TaxId": "userSysNbr",
      "CreateTimestamp": "01:59.5",
      "ModifyTimestamp": null,
      "Keywords": "Ophthalmology; Vitreoretinal Surgery; Minimally Invasive Surgery",
      "Price": "8582",
      "Distance": null
    }
  ]